spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    enableSelfPreservation: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

