server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AntonioDev365/reto-config-service.git
        search-paths:
          - '*service*'

